-- Add all the new fields for social media post request form
ALTER TABLE tasks
ADD COLUMN business_name text,
ADD COLUMN industry text,
ADD COLUMN website_url text,
ADD COLUMN post_type text,
ADD COLUMN objective text,
ADD COLUMN product_service_name text,
ADD COLUMN product_service_images text,
ADD COLUMN product_service_description text,
ADD COLUMN pricing text,
ADD COLUMN post_type_required text,
ADD COLUMN design_style text,
ADD COLUMN brand_colors text,
ADD COLUMN fonts text,
ADD COLUMN logo_url text,
ADD COLUMN headline_main_text text,
ADD COLUMN supporting_text text,
ADD COLUMN cta text,
ADD COLUMN target_audience_age text,
ADD COLUMN target_audience_location text,
ADD COLUMN target_audience_interest text,
ADD COLUMN target_audience_other text,
ADD COLUMN platforms text[],
ADD COLUMN deadline date,
ADD COLUMN notes_extra_instructions text,
ADD COLUMN additional_details text;